name: ML CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Train ML model
        run: |
          pip install scikit-learn
          pip install -r api/requirements.txt 
          python api/model/train.py
          cp api/model/model.pkl api/model.pkl

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/ml-api:latest ./api

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/ml-api:latest

      - name: ArgoCD Sync 
        run: echo "ArgoCD sync would be triggered here."

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "‚úÖ ML API built & deployed successfully!\n\nüìù Commit: ${{ toJson(github.event.head_commit.message) }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
