name: ML CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Train ML model
        run: |
          pip install scikit-learn
          pip install -r api/requirements.txt 
          python api/model/train.py
          cp api/model/model.pkl api/model.pkl

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/ml-api:latest ./api

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/ml-api:latest

      # - name: Deploy to Kubernetes (k3d)
      #   run: |
      #     kubectl set image deployment/ml-api ml-api=${{ secrets.DOCKERHUB_USER }}/ml-api:latest -n mlops

      - name: Update manifest
        run: |
          sed -i "s|image: iamrishabhverma/ml-api:.*|image: iamrishabhverma/ml-api:latest|" k8s/ml-api/deployment.yaml
          git add k8s/ml-api/deployment.yaml
          git commit -m "Update ML API image to latest" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/iamrishabhverma/mlops-cicd-platform.git HEAD:main

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "âœ… ML API built & deployed to Kubernetes successfully!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
